### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/docs#11]
Anbei ein paar SQL die ich geschrieben hab. Funktioniert mit den Timestamp Attributen.

**Alle Einträge die in der Zukunft sind.**

``` sql
SELECT id FROM {{table}} WHERE DATE(FROM_UNIXTIME([[attribute_name]])) >= DATE(now());
```

**Alle in der Zukunft oder gerade laufende.**

``` sql
SELECT id
FROM {{table}}
WHERE 
( DATE(FROM_UNIXTIME([[attribute_name_start]])) >= DATE(NOW()) )
OR
( DATE(FROM_UNIXTIME([[attribute_name_start]])) <= DATE(NOW()) AND DATE(FROM_UNIXTIME([[attribute_name_end]])) >= DATE(NOW()) )
```

**Comment by zonky2** [comment]
übernommen http://metamodels.readthedocs.io/de/latest/cookbook/filter/custom-sql.html

Dank!
