### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by JLBA** [MetaModels/docs#18]
Hello,
I'd like to help you by creating the french translation of MM docs (translating from english one's). How can I do ?

JL BA

**Comment by discordier** [comment]
I'll setup the repository for you.
You should make yourself comfortable with restructured text in the meantime.
We will get back to you in short time.

**Comment by JLBA** [comment]
> I'll setup the repository for you.
> 
Ok
> You should make yourself comfortable with restructured text in the meantime.
> 
What do you mean exactly ?
> We will get back to you in short time.
> 
Ok
>

**Comment by zonky2** [comment]
@JLBA I`ll send you more informations if the rep for french language ready...

**Comment by discordier** [comment]
@zonky2 repository created - please go ahead.

**Comment by zonky2** [comment]
@JLBA pls send me a email (```<look at your github email>```)

**Comment by zonky2** [comment]
https://github.com/MetaModels/docs-fr

**Comment by JLBA** [comment]
Hi Ingolf,

I wanted to go further with fr doc translation but I find sometimes Github desktop interface a little bit confusing. 
1. I don’t understand if or when I have to use merge, sync, commit or something else. More confusing, these buttons aren’t always displayed…
2. I never know if i’m in the Github or my loca	l rep (to sunc with)

How can i create a new rep in local and add again all the files (the translated ones and the others).

Thanks for explanations.

JL Test
jltest@free.fr

**Comment by zonky2** [comment]
Hi JL, which tool do you use? "Github Desktop" or "SourceTree" or other?

**Comment by JLBA** [comment]
Sorry, it looks like my former answer was lost in translation… 
I'm using Github Desktop as my OS X.9.5 is too old for SourceTree.

**Comment by zonky2** [comment]
Ok - I hope, I can explain it...

...you have a local copy of the repository and change any files...

In Github Desktop 
![shot320](https://cloud.githubusercontent.com/assets/1045318/22963589/27066dbc-f354-11e6-9c38-e3d1f53b3cf3.jpg)

1 select your Rep
2 select Changes
3 select yout changed files (if you have) and fill Summary and Description + click Commit
4 click Sync (sync local -> your repository at github)

after this, you should see at your Github account website at rep. docs-fr a green button to send your changes as pull request (PR)

after this work you are ready :-)

I see the the PR at the original repository check and merge them - after few minutes ist the readthedocs website updated...
